# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 */6 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - name: Clone repository
            uses: actions/checkout@v2

          - name: Auto green
            run: |
              git config --local user.email "test@gmail.com"
              git config --local user.name "John"
              git pull --rebase
              date +"%Y-%m-%d %H:%M:%S.%N" > keepchange.txt
              git commit -am "commit by github action"
              git push
